[package]
name = "thsr-ticket-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
opener = "0.7.2"
reqwest = { version = "0.12.11", features = ["blocking", "json", "cookies", "gzip", "brotli", "deflate"] }
scraper = "0.22.0"
